import { CONFIG, FEATURES, DIAGNOSTICS } from './statistics.js';

export function referenceHTML() {
  const sections = [
    ['01 · 왜 무작위를 직접 입력할까요?', `<p>사람은 무작위 수열을 만들 때 0과 1을 지나치게 번갈아 입력하거나 긴 연속 구간을 피하는 경향이 나타날 수 있습니다. <code>0101010101…</code>은 균형 잡혀 있지만 다음 bit를 쉽게 예측할 수 있습니다. 이 실험은 이런 직관과 독립적인 확률 과정의 차이를 체험하기 위해 만들었습니다.</p><p>귀무모형(null model)은 Xᵢ iid ~ Bernoulli(p), i=1,…,100입니다. p는 각 bit가 1일 확률이며, 독립성(independence)은 과거 bit가 다음 bit의 확률을 바꾸지 않는다는 뜻입니다.</p><div class="formula">P(Xᵢ₊₁=1 | Xᵢ=0) = p<br>P(Xᵢ₊₁=1 | Xᵢ=1) = p</div><p>p=0.5라면 두 확률 모두 0.5입니다. 0 뒤에 반드시 1이 나올 이유는 없고, 0000이나 1111도 자연스럽게 나타납니다.</p>`],
    ['02 · 0000이 나오는 것은 왜 자연스러울까요?', `<p>p=0.5일 때 특정 위치에서 시작하는 4개 bit가 모두 0일 확률은 (0.5)⁴ = 1/16 = 6.25%입니다. 1111도 같습니다. 길이 100에는 길이 4의 창(window)이 97개 있으므로 다음과 같습니다.</p><div class="formula">E[N₀₀₀₀] = 97 × 1/16 = 6.0625<br>E[N₁₁₁₁] = 6.0625</div><p>창은 겹칩니다. 예를 들어 00000에는 0000이 두 번 있습니다. 창끼리 독립이지 않아도 기대값의 선형성(linearity of expectation)은 성립합니다. 이 횟수를 독립 시행의 이항분포로 취급하지 않습니다.</p><p>100-bit 수열에 0000이 단 한 번도 없는 것은 통계적으로 unusual할 수 있습니다. 다만 기대 횟수 6.0625 자체는 ‘한 번도 없을 확률’을 뜻하지 않으며, 그 사실만으로 무작위가 아니라고 확정할 수 없습니다. 다른 특성과 함께 해석해야 합니다.</p><div class="formula">P(0000) = (1−p)⁴ &nbsp; P(1111) = p⁴<br>E[N₀₀₀₀] = 97(1−p)⁴<br>E[N₁₁₁₁] = 97p⁴</div><p>결과 화면의 두 히스토그램은 해당 p의 Monte Carlo 분포입니다. 이 두 횟수는 설명용 진단이며 최종 점수에는 직접 포함하지 않습니다.</p>`],
    ['03 · 실제로 측정하는 feature', `<p>아래 ${FEATURES.length}개 통계량을 순서대로 벡터 T에 넣습니다. 모든 패턴은 겹치는 창을 셉니다. 분포 전체는 설정된 p에서 시뮬레이션하며, 아래 식은 가능한 경우의 이론적 기대값입니다.</p>${[...FEATURES, ...DIAGNOSTICS].map((f, i) => `<div class="doc-feature"><h4>${f.group} · ${f.ko} <span class="scope-label">${i < FEATURES.length ? 'JOINT 포함' : '진단 전용'}</span></h4><div class="formula">${f.definition}<br>E[T] = ${f.theory}</div><p>측정 목적: ${f.detects}<br>예시: <code>${f.example}</code></p></div>`).join('')}<p>자기상관(autocorrelation)은 표본 평균 대신 설정된 p로 중심화한 lag product입니다. 표본 Pearson 상관계수와 달라 ±1 범위를 벗어날 수 있고, 상수 수열에서도 계산됩니다. 0과 1의 longest run은 별도로 측정하며 그 bit가 없으면 0입니다.</p>`],
    ['04 · 하나의 joint statistic으로 결합', `<p>통계량들은 정보를 공유합니다. 예를 들어 runs = 1 + N₀₁ + N₁₀이고, 길이 2 패턴 횟수의 합은 99입니다. 독립 Z-score의 제곱합이나 feature 점수 평균은 이 의존성을 무시하므로 사용하지 않습니다.</p><div class="formula">T = (T₁,…,T₁₃)<br>μₚ = E[T], Σₚ = Cov(T)<br>S = (T−μₚ)ᵀ Σₚ⁻¹ (T−μₚ)</div><p>실제로는 ${CONFIG.fitSamples.toLocaleString()}개 학습 시뮬레이션의 평균과 전체 표본 공분산을 사용합니다. 중복으로 인한 특이성(singularity)과 스케일 차이를 처리하기 위해 D=diag(표본 표준편차), C=D⁻¹Σ̂D⁻¹로 정의하고 ridge regularization λ=${CONFIG.ridge}를 적용합니다. 학습 표본에서 분산이 0이면 해당 D 값은 1로 둡니다.</p><div class="formula">z = D⁻¹(T−μ̂ₚ)<br>S = zᵀ(C + ${CONFIG.ridge}I)⁻¹z<br>동치: Σ_reg = Σ̂ + ${CONFIG.ridge}D²</div><p>역행렬을 직접 만들지 않고 Cholesky 분해와 전진 대입으로 S를 구합니다. feature 사이의 공분산을 유지합니다. S는 0 이상이며 커질수록 모형의 중심에서 멀어집니다. 진단 표와 히스토그램은 feature별 독립 배점이 아닙니다.</p>`],
    ['05 · Monte Carlo 보정과 최종 점수', `<p>학습 표본과 별개의 난수 스트림으로 ${CONFIG.calibrationSamples.toLocaleString()}개 보정 표본을 생성합니다. 각 표본에 동일한 feature 추출 및 고정된 공분산 모형을 적용합니다. χ²(카이제곱) 분포를 가정하지 않습니다.</p><div class="formula">Score = 100 × P_null(S ≥ S_user)<br>Score = 100 × (1 + #{S_sim ≥ S_user}) / (N + 1)<br>N = ${CONFIG.calibrationSamples.toLocaleString()}</div><p>모든 feature를 하나의 joint statistic으로 결합한 뒤 그 statistic의 null distribution에서 하나의 점수를 구합니다. 양방향 편차는 이미 quadratic form에 들어 있으므로 two-sided 변환을 다시 하지 않습니다. 동점은 ≥에 포함합니다. 내부 최솟값은 100/(N+1)이며 화면 반올림으로 0.0이 표시될 수 있습니다.</p><ul><li>높은 점수는 선택한 feature에 대해 Bernoulli(p) 중심부에 가깝다는 의미입니다.</li><li>낮은 점수는 해당 귀무모형에서 unusual한 특성이라는 의미입니다.</li><li>실제 random generator가 사용되었을 확률이 아닙니다.</li><li>실제 random generator도 낮은 점수를 받을 수 있습니다. 연속적인 이상적 보정에서는 점수가 대략 균등하게 분포하며, 무작위 수열이 항상 높은 점수를 얻지는 않습니다.</li><li>이산 통계량의 동점 때문에 점수 분포는 보수적(super-uniform)일 수 있습니다. 특히 p가 0 또는 1에 매우 가까우면 같은 수열이 대부분이라 높은 점수에 몰립니다.</li><li>모든 규칙성을 탐지하거나 randomness 자체를 증명하지는 않습니다.</li></ul>`],
    ['06 · p, 캐시, 정확도와 성능', `<p>0 &lt; p &lt; 1 범위의 유한 JavaScript Number를 받습니다. 입력한 수치를 반올림하거나 다른 p로 보간하지 않습니다. 화면의 p와 같은 값으로 모든 시뮬레이션, 기대값, 자기상관 중심화를 계산합니다. JavaScript 표현 범위 밖의 값이나 0·1로 반올림되는 값은 거부합니다.</p><p>Web Worker가 설정 단계에서 총 ${(CONFIG.fitSamples + CONFIG.calibrationSamples).toLocaleString()}개 수열을 계산합니다. 보정이 준비된 뒤 게임을 시작하므로 완료 즉시 점수를 낼 수 있습니다. 버전·정확한 p를 키로 IndexedDB와 메모리에 최근 6개 모형을 보관합니다. 캐시 사용이 불가능하면 메모리만 사용합니다. 설정을 바꾸면 이전 작업을 취소합니다.</p><p>시뮬레이션은 p와 버전으로 seed를 정한 재현 가능한 의사난수(pseudorandom) 스트림을 사용합니다. 암호학적 난수 보장이 목적이 아니며, 유한 난수 정밀도와 유한 표본의 한계가 있습니다. ${CONFIG.calibrationSamples.toLocaleString()}개 표본에서 확률 0.5 부근의 보정 Monte Carlo 표준오차는 약 ${(100 * Math.sqrt(0.25 / CONFIG.calibrationSamples)).toFixed(2)}점입니다. 이는 평균·공분산 추정 불확실성을 포함한 전체 오차 한계가 아닙니다.</p><p class="warning-note">p가 0 또는 1에 매우 가까우면 희귀 사건이 학습·보정 표본에 나타나지 않을 수 있습니다. ridge는 계산을 안정화할 뿐 희귀 사건의 정확한 꼬리 확률을 복원하지는 않습니다. 이런 설정의 점수는 특히 거칠고 이산적입니다.</p><p>100개가 완성되는 순간 입력이 잠깁니다. 제한시간이 먼저 끝나면 현재 개수와 수열만 표시하고 정식 점수나 100-bit 진단을 계산하지 않습니다. 설명 창을 열어도 진행 중인 시간은 멈추지 않습니다.</p><div class="formula">모형 버전: ${CONFIG.version}<br>길이: ${CONFIG.length} · 차원: ${FEATURES.length}<br>학습: ${CONFIG.fitSamples} · 보정: ${CONFIG.calibrationSamples}<br>ridge: ${CONFIG.ridge} · lag: 1–${CONFIG.maxLag}</div>`],
  ];
  sections[5][1] += '<p>표현 가능한 극단적인 p에서 관측 통계량 계산이 부동소수점 범위를 넘으면 S를 Infinity로 표시하고, 모든 유한 보정 표본보다 큰 값으로 취급해 최소 경험 점수를 줍니다. 이는 실수 수학의 S가 무한하다는 뜻이 아니라 수치 표현의 한계입니다.</p>';
  sections[5][1] += '<p>브라우저 호환성: 캐시 작업이 1.5초 내 응답하지 않으면 캐시를 건너뜁니다. Worker 오류 또는 15초간 진행 응답이 없으면 같은 알고리즘을 화면 스레드에서 500개 표본씩 나누어 계산하는 호환 모드로 전환합니다. 표본 수·난수·점수 정의는 바뀌지 않습니다.</p>';
  return sections.map(([title, body], i) => `<details ${i === 0 ? 'open' : ''}><summary>${title}</summary>${body}</details>`).join('');
}
